// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgiGwheRB8PiPx0GKt9-azqZ8Yslvea64',
    appId: '1:485804141750:web:cbbe7ca8674fe947690a17',
    messagingSenderId: '485804141750',
    projectId: 'shamba-fresh',
    authDomain: 'shamba-fresh.firebaseapp.com',
    storageBucket: 'shamba-fresh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzB829TQoQfsT0Pf254OQRMF6S2snExSw',
    appId: '1:485804141750:android:8f8ba19d641e24bf690a17',
    messagingSenderId: '485804141750',
    projectId: 'shamba-fresh',
    storageBucket: 'shamba-fresh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIJLffVKimEkP64lnsAKTWQ1IQ-p_i9iw',
    appId: '1:485804141750:ios:42bd2bf5a95f345a690a17',
    messagingSenderId: '485804141750',
    projectId: 'shamba-fresh',
    storageBucket: 'shamba-fresh.appspot.com',
    iosClientId: '485804141750-r6k2uorkpmnub03p8ft7gbitb6cbhjel.apps.googleusercontent.com',
    iosBundleId: 'com.gabina.wabayetu.wabayetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIJLffVKimEkP64lnsAKTWQ1IQ-p_i9iw',
    appId: '1:485804141750:ios:42bd2bf5a95f345a690a17',
    messagingSenderId: '485804141750',
    projectId: 'shamba-fresh',
    storageBucket: 'shamba-fresh.appspot.com',
    iosClientId: '485804141750-r6k2uorkpmnub03p8ft7gbitb6cbhjel.apps.googleusercontent.com',
    iosBundleId: 'com.gabina.wabayetu.wabayetu',
  );
}
